version: "3.8"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=geolife
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: exercise3
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DATABASE=geolife
    command: tail -f /dev/null

volumes:
  mongodb_data:
