version: "3.8"

services:
  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: group20
      MYSQL_DATABASE: geolife
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: exercise2
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=geolife
      - MYSQL_USER=root
      - MYSQL_PASSWORD=group20
    command: tail -f /dev/null
volumes:
  mysql_data:
